name: End-to-end Tests

on: [pull_request]


jobs:

  e2e_test:
    strategy:
      matrix:
        include:
        - xcodeVersion: 11.7
          deviceName: iPhone 11
        - xcodeVersion: 12.4
          deviceName: iPhone X
        - xcodeVersion: 13.2
          deviceName: iPhone X
    env:
      CI: true
      _FORCE_LOGS: 1
      DEVICE_NAME: ${{ matrix.deviceName }}
      XCODE_VERSION: ${{ matrix.xcodeVersion }}
    # https://github.com/actions/runner-images/tree/main/images/macos
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        check-latest: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ matrix.xcodeVersion }}"
    - run: npm install
      name: Install dev dependencies
    - run: npm run e2e-test
      name: Run e2e tests on Xcode@${{ matrix.xcodeVersion }}
